# Generated by Django 3.2.2 on 2021-06-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancy_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='written_number',
            new_name='written_phone',
        ),
    ]
