# Generated by Django 3.2.2 on 2021-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('Не ищу работу', 'Не ищу работу'),
                                            ('Рассматриваю предложения', 'Рассматриваю предложения'),
                                            ('Ищу работу', 'Ищу работу')],
                                   default='Ищу работу',
                                   max_length=32),
        ),
    ]
